name: Feature Suggestion
description: Suggest a new feature for the Crochet Stitch Tracker App.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the Feature / Enhancement
      description: A clear and concise description of the feature to be added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details and Resources
      description: Provide as much detail about this proposed change as you can, including links to lines of code, issues, PRs, and external resources where possible.
